logging:
    file:
        name: logs/ch09.log
    level:
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8080
    servlet:
        context-path: /ch09
spring:
    application:
        name: ch09
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        password: TnsRnjs231123
        url: jdbc:oracle:thin:@//15.165.32.191:1522/XEPDB1
        username: sundae517
    devtools:
        livereload:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

jwt:
    issuer: link8430@gmail.com
    secret: 6AFE74689A754C9DDD5EC97A3923D88ab